name: sheetify
description: "A Flutter package that provides customizable bottom sheet widgets with snapping behaviors, gesture support, animation, and dynamic state control."
version: 1.1.3

repository: https://github.com/urbi-ae/sheetify
homepage: https://github.com/urbi-ae/sheetify

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=2.17.0"

dependencies:
  flutter:
    sdk: flutter
  keyboard_insets: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0